### ISSUE TITLE
Elimina Commenti

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Eliminacommenti#1]
Scrivere un programma che elimina i commenti da un file C

**Comment by FabioZTessitore** [comment]
Il programma non supera il test della divisione

**Comment by FabioZTessitore** [comment]
hai bisogno di aiuto?

**Comment by FabioZTessitore** [comment]
ci sei? che ne dici di proseguire?

**Comment by lucifero55** [comment]
si ho bisogno di una mano, ho un problema con gli '/'

**Comment by FabioZTessitore** [comment]
Il problema che stai affrontando non è banale se provi a trovare una soluzione come stai facendo. Invece diventa estremamente semplice se si usa un diagramma degli stati. Siccome non sai di che sto parlando ti faccio un esempio relativo al problema degli spazi multipli.

Dimmi se ti è chiaro

#### Stato *Carattere*

Input | Output | Prossimo Stato
-------|----------|--------------------
`c!=' '` | `c` | *Carattere*
`c==' '` | `c` | *Spazio*


#### Stato *Spazio*
Input | Output | Prossimo Stato
-------|----------|--------------------
`c!=' '` | `c` | *Carattere*
`c==' '` | `NULL` | *Spazio*

**Comment by lucifero55** [comment]
fatto

Il giorno 4 gennaio 2016 22:48, Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
Quando si usa una variabile che puo' assumere solo certi valori,
invece di usare i numeri si puo' creare una enum (una lista di nomi)

```c
enum stato { CARATTERE, ASTERISCO, COMMENTO ecc ecc};
```

A questo punto puoi dichiarare una variabile di tipo enum stato con
```c
enum stato Stato = CARATTERE;
```

Quindi invece di usare i numeri puoi fare confronti con
```c
if (stato==CARATTERE) ...
```

Prova

Inoltre cerca di non fare tante if slegate tra di loro. Usa if-else if

Il giorno 8 gennaio 2016 16:31, lucifero55 <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Quando si usa una variabile che puo' assumere solo certi valori,
invece di usare i numeri si puo' creare una enum (una lista di nomi)

```c
enum stato { CARATTERE, ASTERISCO, COMMENTO ecc ecc};
```

A questo punto puoi dichiarare una variabile di tipo enum stato con
```c
enum stato Stato = CARATTERE;
```

Quindi invece di usare i numeri puoi fare confronti con
```c
if (stato==CARATTERE) ...
```

Prova

Inoltre cerca di non fare tante if slegate tra di loro. Usa if-else if

**Comment by FabioZTessitore** [comment]
Come ti dicevo nel posto precedente, ci sono tanti if slegati. In più alcuni di essi dipendono dall'ordine in cui si trovano. Un programma così fatto non è facile da gestire perché ogni volta uno se lo deve ristudiare.

Cerca di fare una sequenza di if - else if ... - else. Un ramo per ogni stato. All'interno poi di ogni ramo ci metti la logica associata a quello stato.

**Comment by lucifero55** [comment]
fatto
